Works and about section
Cisco-the-wayword/Portfolio-Website pull request #2
Opened 2022-08-27 22:00 UTC by Cisco-the-wayword

- Added works section
- Added about section
- Implemented button
- Ran and passed linter tests
- Tested the website to see how well it works

2022-08-27 23:30 UTC, zieeco requested changes
Hi @Cisco-the-wayword,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A


**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 23:30 UTC, zieeco commented on index.html
> +        </div>
- Please, kindly use the ul tag and add its list items as this is are list of skills, using the ul will enable you to enforce the use of html5 semantic tag correctly

2022-08-27 23:30 UTC, zieeco commented on index.html
> +        </div>
- Please, kindly use the ul tag and add its list items as this is are list of skills, using the ul will enable you to enforce the use of html5 semantic tag correctly

2022-08-27 23:30 UTC, zieeco commented on index.html
> +          </div>
- Please, kindly use the ul tag and add its list items as this is are list of skills, using the ul will enable you to enforce the use of html5 semantic tag correctly

2022-08-27 23:30 UTC, zieeco commented on index.html
> +        </div>
- Please, kindly use the ul tag and add its list items as this is are list of skills, using the ul will enable you to enforce the use of html5 semantic tag correctly

2022-08-27 23:30 UTC, zieeco commented on index.html
> +        </div>
- Please, kindly use the ul tag and add its list items as this is are list of skills, using the ul will enable you to enforce the use of html5 semantic tag correctly

2022-08-27 23:30 UTC, zieeco commented on index.html
> +        <div class="post">Multi-Post Stories Gain+Glory</div>
- Please, consider using an h2-h6 tag here, as this is the header and not a div item.

2022-08-27 23:30 UTC, zieeco commented on index.html
> +        <div class="post">Multi-Post Stories Gain+Glory</div>
- Please, consider using an h2-h6 tag here, as this is the header and not a div item.

2022-08-27 23:30 UTC, zieeco commented on index.html
> +        <div class="post">Multi-Post Stories Gain+Glory</div>
- Please, consider using an h2-h6 tag here, as this is the header and not a div item.

2022-08-27 23:30 UTC, zieeco commented on index.html
> +        <div class="post">Multi-Post Stories Gain+Glory</div>
- Please, consider using an h2-h6 tag here, as this is the header and not a div item.

2022-08-27 23:30 UTC, zieeco commented on index.html
> +          </div>
- Please, kindly use the ul tag and add its list items as this is are list of skills, using the ul will enable you to enforce the use of html5 semantic tag correctly

2022-08-27 23:30 UTC, zieeco commented on index.html
> +        <div class="post">Multi-Post Stories Gain+Glory</div>
- Please, consider using an h2-h6 tag here, as this is the header and not a div item.

2022-08-28 00:43 UTC, mukhammadrizooff requested changes
Hi @Cisco-the-wayword, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-28 00:43 UTC, mukhammadrizooff commented on styles.css
> +}
- [ ] [REQUIRED] Good job so far! Please fix the style error highlighted in the image below!

![image](https://user-images.githubusercontent.com/63915024/187052860-8ff5f900-b6d4-4e6b-af4e-b4d11fb3d9f2.png)

2022-08-28 00:58 UTC, mukhammadrizooff approved these changes
Hi @Cisco-the-wayword, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/sR9nilEznDoSlga667/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Perfect design ✔️ 
- Good implementations ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-28 01:01 UTC, merged